language: node_js
script: true
node_js:
- lts/*
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3d57bec00f39_key -iv $encrypted_3d57bec00f39_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- echo -e "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- docker build . -t "nasyalnik/cats-ui:travis-$TRAVIS_BUILD_NUMBER"
deploy:
  provider: script
  script: bash travis/docker
  on:
    branch: master
